MODEL:
  DATA_DIM: 100
  SEQ_LEN: 100
  READIN_DIM: 50
  IC_ENC_DIM: 100
  CI_ENC_DIM: 100
  CON_DIM: 100
  CO_DIM: 4
  IC_DIM: 100
  GEN_DIM: 100
  FAC_DIM: 30
  DROPOUT_RATE: 0.1 # PBT
  CD_RATE: 0.5 # PBT
TRAIN:
  DATA:
    DIR: ''
    PREFIX: lfads
    # AUGMENT:
    #   JITTER: 2
  PATIENCE: 10000
  BATCH_SIZE: 1000
  ADAM_EPSILON: 1.0e-8
  LR: 
    INIT: 1.0e-3 # PBT
    STOP: 1.0e-10
    DECAY: 1.0
  L2:
    INCREASE_EPOCH: 100
    GEN_SCALE: 1.0e-6 # PBT
    CON_SCALE: 1.0e-6 # PBT
  KL:
    INCREASE_EPOCH: 100
    IC_WEIGHT: 1.0e-6 # PBT
    CO_WEIGHT:  1.0e-6 # PBT
  TUNE_MODE: True
  PBT_MODE: True
  USE_TB: False
  MODEL_DIR: ~/tmp/lfads_tf2/nomad
