MODEL:
  DATA_DIM: 50
  SEQ_LEN: 100
  READIN_DIM: 0
  IC_ENC_DIM: 100
  CI_ENC_DIM: 64
  CON_DIM: 64
  CO_DIM: 10
  IC_DIM: 100
  GEN_DIM: 100
  FAC_DIM: 40
  DROPOUT_RATE: 0.05 # OVERWRITTEN
  CD_RATE: 0.5 # OVERWRITTEN
  CD_PASS_RATE: 0.0 # OVERWRITTEN
  SV_RATE: 0.0
  SV_SEED: 0
  CO_PRIOR_TAU: 10.0
  CO_PRIOR_NVAR: 0.1
  IC_PRIOR_VAR: 0.1
  IC_POST_VAR_MIN: 1.0e-4
  CELL_CLIP: 5.0
  CI_LAG: 1
TRAIN:
  DATA:
    DIR: /snel/share/runs/PBT/paper-fix/lfadslite-testing/data_chaotic
    PREFIX: chaotic
  PATIENCE: 5000 # Early stopping should be off
  BATCH_SIZE: 200
  MAX_EPOCHS: 10000
  MAX_GRAD_NORM: 200.0
  LOSS_SCALE: 10000.0
  LR: 
    INIT: 0.01 # OVERWRITTEN
    STOP: 1.0e-5
    DECAY: 0.95
    PATIENCE: 6
  ADAM_EPSILON: 1.0e-8
  L2:
    START_EPOCH: 0
    INCREASE_EPOCH: 50
    IC_ENC_SCALE: 1.0e-4 # OVERWRITTEN
    CI_ENC_SCALE: 1.0e-4 # OVERWRITTEN
    GEN_SCALE: 1.0e-4 # OVERWRITTEN
    CON_SCALE: 1.0e-4 # OVERWRITTEN
  KL:
    START_EPOCH: 0
    INCREASE_EPOCH: 50
    IC_WEIGHT: 1.0e-4 # OVERWRITTEN
    CO_WEIGHT:  1.0e-4 # OVERWRITTEN
  EAGER_MODE: False
  TUNE_MODE: True
  USE_TB: False
  MODEL_DIR: ~/tmp/lfads_tf2/validation # OVERWRITTEN
  OVERWRITE: True
